# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    build: ./database/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ADDHERE
      MYSQL_DATABASE: c279
      MYSQL_USER: c279-user
      MYSQL_PASSWORD: ADDHERE


  node:
    build: ./backend/
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend/app.js:/usr/src/app/app.js
    command: bash -c 'sleep 5; node app.js'
    links:
      - "db:db"


  express:
    build: ./tech-demonstrator/
    ports:
      - "3001:3001"
    depends_on:
      - node
    volumes:
      #don't mount the root directory containing 'node_modules'
      - ./tech-demonstrator/src/:/usr/src/app/src/
      - ./tech-demonstrator/public/:/usr/src/app/public/
    links:
      - "node:node"
